### ISSUE TITLE
Doesn't work , i think a package is missing and that makes the script ends prematurally without installing packages

### ISSUE THREAD

**Issue by Switched2BSD** [nicholasbernstein/install-fbsd-desktop#3]
A package is missing and that makes the script ends prematurally without installing packages it doesn't work don't know what is the problem maybe something about a drivers package (nvidia) or something else ?

**Comment by nicholasbernstein** [comment]
Can you send me the error that you get?

**Comment by supremelinux** [comment]
Yes i will check it i think i know what is the problem but i didn't write it down and i forgot it.
This script is very helpful .
I usually had to install some pkgs do some configs while they download then download some more that i needed some more and some rules etc. The pkg download speed is not good like other linux distos dragonfly has nice pkg download speed.

**Comment by Switched2BSD** [comment]
Its the hal package who causes the problem !

**Comment by nicholasbernstein** [comment]
fixed
