### ISSUE TITLE
installx.sh runs and stops

### ISSUE THREAD

**Issue by piranah** [nicholasbernstein/install-fbsd-desktop#5]
Hi Nicholas,

Excellent script, looked at it and love it. I run FreeBSD 13.1

The script starts, asks a few questions until the hardenings window, carries on then stops mid air after I say 'yes' to video drivers, runs further and quits with the finish screen. If I say 'no' to the graphics drivers question, the script continues as it should and runs the full length.

**Comment by nicholasbernstein** [comment]
Can you send me the installx.log that gets created in the directory you run the script? Also, what driver are you selecting? It's possible that the name of the package has changed and the install is failing. 

There is a line in the log which lists all of the packages that are being installed, you can also run that and see if it gives you an error about a driver breaking. 

Thanks for the feedback.

**Comment by nicholasbernstein** [comment]
can't reproduce w/o further info
